// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3zIwYpfiZiIb3Lw_Wva8SliexsZZIsc',
    appId: '1:473271336583:web:812a8f36cc01578347c222',
    messagingSenderId: '473271336583',
    projectId: 'fir-storageapp-224d3',
    authDomain: 'fir-storageapp-224d3.firebaseapp.com',
    storageBucket: 'fir-storageapp-224d3.appspot.com',
    measurementId: 'G-34W9BTXV24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo7OO0uKtBRFkLvRNi-cbqETkIqgWitB0',
    appId: '1:473271336583:android:256d6bfe827726c047c222',
    messagingSenderId: '473271336583',
    projectId: 'fir-storageapp-224d3',
    storageBucket: 'fir-storageapp-224d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNmoW9Ult5dH2jz5X6hV-aOkR3ve3YUU8',
    appId: '1:473271336583:ios:5e0d503043ead32c47c222',
    messagingSenderId: '473271336583',
    projectId: 'fir-storageapp-224d3',
    storageBucket: 'fir-storageapp-224d3.appspot.com',
    iosBundleId: 'com.example.firebaseStorageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNmoW9Ult5dH2jz5X6hV-aOkR3ve3YUU8',
    appId: '1:473271336583:ios:a37d9f9372d9501d47c222',
    messagingSenderId: '473271336583',
    projectId: 'fir-storageapp-224d3',
    storageBucket: 'fir-storageapp-224d3.appspot.com',
    iosBundleId: 'com.example.firebaseStorageApp.RunnerTests',
  );
}
